# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  # adapter: postgresql
  # encoding: unicode
  # database: home_db
  # pool: 5
  # username: root
  # password: root
  adapter: mysql2
  encoding: utf8
  database: blog
  pool: 5
  host: localhost
  username: root
  password: nanohealth321